# version: '3.8'

services:
  backend:
    build: ./backend
    container_name: back
    # restart: always
    ports:
      - "5000:5000"
    
  frontend:
    build: ./frontend
    container_name: front
    # restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend